site_name: Koor Storage Distribution Documentation
docs_dir: Documentation/
site_url: "https://docs.koor.tech"
repo_url: https://github.com/koor-tech/koor
edit_uri: edit/master/Documentation/
site_author: Rook Authors
site_description: "Koor Documentation"
use_directory_urls: true
copyright: |
  Copyright &copy; 2022 Koor Technologies, Inc. All Rights Reserved.
  <br>
  Rook is a trademark of The Linux Foundation®.
  <br>
  Ceph is a trademark or registered trademark of Red Hat, Inc. or its subsidiaries in the United States and other countries.
  <br>
  All trademarks are property of their respective owners in the US and other countries.
theme:
  name: material
  custom_dir: .docs/overrides/
  font: false
  favicon: https://koor.tech/images/favicon.svg
  logo: https://koor.tech/images/logo.svg
  palette:
    scheme: "default"
  icon:
    repo: fontawesome/brands/github
  features:
    - content.tabs.link
    - instant
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - tabs
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - exclude:
      glob:
        - README.md
  - awesome-pages
  - macros:
      module_name: .docs/macros/includes/main
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
      #js_files: []
  - redirects:
      redirect_maps:
        README.md: Getting-Started/intro.md
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true # set to false to leave out the version selector
      css_dir: css # the directory to put the version selector's CSS
      javascript_dir: js # the directory to put the version selector's JS
      canonical_version:
        null # the version for <link rel="canonical">; `null`
        # uses the version specified via `mike deploy`
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed
extra:
  version:
    provider: mike
    default: latest-release
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/koor_tech
    - icon: fontawesome/brands/medium
      link: https://koor.tech/blog/
