apiVersion: v2
description: Manages a single Ceph cluster namespace for Rook
name: rook-ceph-cluster
version: 0.0.1
appVersion: 0.0.1
icon: https://koor.tech/images/logo.svg
sources:
  - https://github.com/koor-tech/koor
dependencies:
  - name: library
    version: "0.0.1"
    repository: "file://../library"
  - name: extended-ceph-exporter
    version: "1.1.0"
    repository: "https://koor-tech.github.io/extended-ceph-exporter"
    condition: extendedCephExporter.enabled
