apiVersion: v2
description: File, Block, and Object Storage Services for your Cloud-Native Environment
name: rook-ceph
version: 0.0.1
appVersion: 0.0.1
icon: https://koor.tech/images/logo.svg
sources:
  - https://github.com/koor-tech/koor
dependencies:
  - name: library
    version: "0.0.1"
    repository: "file://../library"
